version: '2'

services:
  app:
    image: 'tinkoff-academy-app:latest'
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mongodb
      - redis
    environment:
      - SPRING.DATASOURCE.URL=jdbc:postgresql://db/postgres
      - SPRING.DATA.MONGODB.URI=mongodb://mongodb/app
      - SPRING.DATA.REDIS.HOST=redis
      - MINIO.URL=http://minio

  db:
    image: 'postgres:16-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=app
    volumes:
      - ./environment/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - app-mongodb:/data/db
      - app-mongo-config:/data/configdb

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --logLevel warning --requirepass YXNkZmFzZGY=
    volumes:
      - app-redis:/data

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./environment/minio/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address :9001

volumes:
  postgres:
  app-mongodb:
  app-mongo-config:
  app-redis:
  storage-minio: